# Generated by Django 4.1.7 on 2023-03-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbar', '0002_salesrecord_sold_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='day_name',
            field=models.CharField(default=1, editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
