# Generated by Django 4.1.7 on 2023-03-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbar', '0003_salesrecord_day_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='day_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
